### ISSUE TITLE
Weber iGrill V2 not detected

### ISSUE THREAD

**Issue by kvoit** [1mckenna/esp32_iGrill#13]
I have a Weber iGrill V2 that I recently bought in Germany. Unfortunately, it isn't discovered. In MyAdvertisedDeviceCallbacks::onResult, I added an else statement with a Serial output that tells me that in principle, the iGrill is discoved and haveServiceUUID is true. Thus, I assume the Service UUID of my devise is different from the expected ones.
Any hint on how I find the service UUIDs that are actually advertise, so I can proceed testing?

Thanks for the great work, anyway.

**Comment by 1mckenna** [comment]
I just added support for the newer iGrillv2 devices a couple days ago, when did you last pull the code? 

If its still not working can you do the following steps and take a screenshot/attach the logs so I can look and see what the UUID your device is using.

1. Install the nrfConnect Android App
2. Once in the App Click on the Bonded Tab
3. You should see your iGrill listed, click Connect
4. It should then go through discovery of the services (this is the info I'll need).

**Comment by kvoit** [comment]
It works with the most recent update. Thanks and sorry to bother you!

I wasn't completely up-to-date as I changed the code a bit to be able to flash it with PlatformIO.

**Comment by 1mckenna** [comment]
Awesome glad to hear it's working for you!

**Comment by gazelle-hub** [comment]
Not quite sure to export this to a file but here's a screenshot, unless you can tell me?
![Screenshot_20220205-124652_nRF Connect](https://user-images.githubusercontent.com/53669961/152617906-604cc24b-fb08-4e50-9e8d-e64567cb4fe9.jpg)
