### ISSUE TITLE
How do you pair an iGrill to your board once flashed?

### ISSUE THREAD

**Issue by gazelle-hub** [1mckenna/esp32_iGrill#15]
Hi there,

This is really awesome but I can't figure out you pair my iGrill to my esp32 board? There doesn't seem to be any mention of this in your readme file, unless I am missing something?

Thanks in advance for your help.

**Comment by 1mckenna** [comment]
Unlike when using the iGrill Android/iOS app you won't need to manually pair the devices (the esp32_iGrill code handles this automatically). Once the iGrill has connected to the esp32 the blue led on the iGrill device should go solid blue (at least it does on my gen1 iGrillv2 device).

**Comment by gazelle-hub** [comment]
So it should just detect that there is an igrill near it and connect?

**Comment by 1mckenna** [comment]
Correct

**Comment by gazelle-hub** [comment]
I've got the iGrill mini and it doesn't seem to connect.

I'm looking at the logs and I can see the my board (M5 Atom Lite) is scanning for devices but it doesn't connect.

I've tried restting the iGrill mini to factory settings but it still doesn't connect.

**Comment by 1mckenna** [comment]
Can you move the mini next to the esp to make sure its not a BT range issue? Also you may want to double check if you have paired the device to your phone before that you remove the pairing so the phone doesn't try to connect. 

How new is the iGrill mini device (wondering if the new ones have a different service UUIDs similar to the iGrill2 v2 devices)?

**Comment by gazelle-hub** [comment]
They're sitting right next to each other while I try and set them up.

I had factory reset the iGrill mini and also removed the app completely. Just redownloaded the app to check and it doesn't have any connnections.

I bought it a couple of weeks ago.

**Comment by 1mckenna** [comment]
Can you follow the steps [here](https://github.com/1mckenna/esp32_iGrill/issues/13#issuecomment-944920706) and attach the output?

**Comment by gazelle-hub** [comment]
Sorry posted on wrong issue.

Here's a screenshot as I'm not sure how to export the info.
![Screenshot_20220205-124652_nRF Connect](https://user-images.githubusercontent.com/53669961/152618106-4cdf4a94-5e71-4034-b1fd-8f328d963306.jpg)

**Comment by gazelle-hub** [comment]
Here's the xml file in txt format
[iGrill_MINI02-79B9 - copy.txt](https://github.com/1mckenna/esp32_iGrill/files/8006904/iGrill_MINI02-79B9.-.copy.txt)
.

**Comment by 1mckenna** [comment]
I just pushed an updated version to the mini_v2 branch that should work now. Can you switch to that branch, flash that version and let me know the results?

**Comment by gazelle-hub** [comment]
Thats working great now.

Thanks very much for all of your efforts.

**Comment by 1mckenna** [comment]
Awesome! iGrill_mini_v2 changes are now merged into the main branch.

Thanks!
