### ISSUE TITLE
Propane Service: electrical details needed

### ISSUE THREAD

**Issue by LukasQ** [1mckenna/esp32_iGrill#20]
Dear all

Unfortunately my iGrill3 was sold without a fuel integration here in Europe. I think mainly bc of the different tanks.
Still, I want to have a propane level indicator in HA and it seems like you can't buy them.
Could one please check the iGrill signals on that iGrill3 jack, so I can hack and 3D print an open source solution?
Spoiler: I tried load cells already. Even though they seem pretty cool, they're also pretty temperature sensitive, which is to me an issue an the BBQ ;)

Cheers, Lukas

**Comment by 1mckenna** [comment]
I don't have an iGrill3/haven't seen one in person to know enough about how the propane level sensor portion works. Maybe someone with an iGrill3 can reply and provide some more info on how that part works.

**Comment by LukasQ** [comment]
I recreated one with a spring and a sliding potentiometer and updated your code with an ADC and a some basic math. Should do the trick, at least more precise than a 1/4 scale.
![grafik](https://user-images.githubusercontent.com/5947912/188475147-fe2ff50c-a7a0-4e76-8ef4-6996a06bcb2e.png)
