### ISSUE TITLE
Integration with ESPHome

### ISSUE THREAD

**Issue by Daedilus** [1mckenna/esp32_iGrill#25]
As my coding skills are limited, is there a way to integrate this with ESPHome? It would allow someone to use the low power bluetooth options already combined and then allow the ESP32 device to be used for multiple applications without having it as a standalone device that only does iGrill.

**Comment by sn3ak** [comment]
@mwolter805 posted an ESPHome configuration [here](https://github.com/esphome/issues/issues/3319).
It may be unnecessary to integrate this with ESPHome. At the time that configuration was posted mwolter805 was having issues with the battery reporting though.
Having just stumbled across this myself, I will hopefully be trying it later this evening.

@mwolter805, If you were able to resolve this issue with a configuration change would you be so kind to share it with us?

**Comment by sn3ak** [comment]
So far battery state works fine. I am unable to get the probes to report temperature.

I get the following in Logs:
```
[I][esp32_ble_client:154]: [0] [d4:81:ca:20:6a:03] Service UUID: A5C50000-F186-4BD6-97F2-7EBACBA0D708
[D][sensor:127]: 'Weber iGrill 2 Probe 1': Sending state nan °F with 0 decimals of accuracy
[W][ble_sensor:049]: No sensor characteristic found at service ADA7590F-2E6D-469E-8F7B-1822B386A5E9 char 06EF0002-2E06-4B79-9E33-FCE2C42805EC
```
This is because my service UUID is different as show above. 

Changing the service UUID results in a different error:
```
[W][ble_sensor:080]: Error reading char at handle 52, status=2
[W][ble_sensor:080]: Error reading char at handle 52, status=2
[W][ble_sensor:080]: Error reading char at handle 52, status=2
[W][ble_sensor:080]: Error reading char at handle 52, status=2
[W][ble_sensor:080]: Error reading char at handle 52, status=2
```

**Comment by 1mckenna** [comment]
In order to get the temperature probe values you have to authenticate/pair with the device. If ESPHome supports that then it should be possible.
