### ISSUE TITLE
Home Assistant Deprecation warnings

### ISSUE THREAD

**Issue by dkowis** [1mckenna/esp32_iGrill#32]
![image](https://github.com/1mckenna/esp32_iGrill/assets/28048/1aab1baa-9cff-457f-84a4-cdbc19f3dd0f)

I updated to Homeassistant 2023.8.0 today, and this warning showed up. I'm not sure yet if it's a problem I can just fix, or if it should be brought up here, but I'll go ahead and start this issue and update it if I figure something out, or if it gets fixed here :)

[HomeAssistant developers blog link](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/)

Thanks!

**Comment by 1mckenna** [comment]
Thanks for letting me know I hadn't had a chance to update to 2023.8 yet.

Looks like I'll need to make a slight change to the MQTT auto-discovery code. I'll work on getting an updated version out at some point over the next few days.

**Comment by 1mckenna** [comment]
I've made the code updates and verified they are working on my end. Can someone else test the (discoveryUpdates)[https://github.com/1mckenna/esp32_iGrill/tree/discoveryUpdates] branch and verify it looks good on your end as well?

**Comment by donoghdb** [comment]
@1mckenna this looks like its working as its gone off the repair list on HA. Thank you

**Comment by dkowis** [comment]
I'll update my device today. It's been a busy week.

EDIT: I failed at updating my device yesterday, aiming for today again :|

**Comment by dkowis** [comment]
I have updated my device as well, and after a restart of HomeAssistant, that warning has been cleared. I see probe temps and battery levels and all the goodies.

**Comment by dkowis** [comment]
~~Well, I only see 1 probe even though I have two probes plugged in.... I don't remember if I've actually ever used it with more than one probe attached at once, but I only ever see one probe in homeassistant. I can move it through all 4 ports, and that tells me probe 1-4, but if I plug in a second probe, I don't see that temp reported.~~

well, of course, as soon as I send that message, it starts behaving itself. I see two probe temperatures now as soon as I plug them in. I must've caught it in an upset state or something.

**Comment by 1mckenna** [comment]
Awesome thanks for testing! I'll go ahead and push out these changes to the main branch shortly.

**Comment by 1mckenna** [comment]
Code has been pushed to [main](https://github.com/1mckenna/esp32_iGrill/pull/34)
