### ISSUE TITLE
Bluetooth Error

### ISSUE THREAD

**Issue by donoghdb** [1mckenna/esp32_iGrill#33]
<img width="744" alt="Screenshot 2023-08-04 at 15 56 45" src="https://github.com/1mckenna/esp32_iGrill/assets/85128952/8796f081-8882-4b3c-b018-ac7edbef6a37">

I get the following error when the ESP32 connects to my IGrill 3.

Any idea what is causing it?

Thank you

**Comment by 1mckenna** [comment]
Which version of the esp32 board library are you using? There are issues with versions > 2.0.4 .

**Comment by donoghdb** [comment]
I will need to check. What version do you recommend?

**Comment by 1mckenna** [comment]
Try version 2.0.4

**Comment by donoghdb** [comment]
My arduino IDE's wont compile this as i get the follow error ('BLEUUID' does not name a type; did you mean 'BLUE_LED') so I use PlatformIO. 

The libraries I installed are below and the framework is 2.0.4 as shown below and the issue is still there. 

`CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.1.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.20004.220825 (2.0.4) 
 - tool-esptoolpy @ 1.30300.0 (3.3.0) 
 - tool-mkfatfs @ 2.0.1 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 2.230.0 (2.30) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Converting esp32_iGrill.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.21.3
|-- PubSubClient @ 2.8.0
|-- ESP_DoubleResetDetector @ 1.3.2
|-- ESP_WifiManager @ 1.12.1
|-- ESP32 BLE Arduino @ 2.0.0
|-- LittleFS @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode`

I tried the latest version 2.0.9 and the issue is still there.

**Comment by 1mckenna** [comment]
I haven't used PlatformIO so I am not familiar with it's setup, but that error likely means that its not finding the BLEDevice.h file that's a part of the esp32 board library.

**Comment by donoghdb** [comment]
Any idea to get rid of this compile error on Arduino IDE 'BLEUUID' does not name a type; did you mean 'BLUE_LED'?
I can try the IDE then to see if the error persists?

**Comment by 1mckenna** [comment]
Have you followed the setup steps [here](https://github.com/1mckenna/esp32_iGrill#arduino-ide-setup)?

**Comment by donoghdb** [comment]
@1mckenna I figured out the issue, I had multiple BLEDevice.h libraries and it was taking the wrong one. I had to delete the other library.
