### ISSUE TITLE
Which hardware to use?

### ISSUE THREAD

**Issue by diverflo89** [1mckenna/esp32_iGrill#39]
H guys. 
I finally got the compiler in line, so it stops complaining. 
I tried to load this on an Arduino Nano ESP32. 
I also swapped it for an Arduino UNO R4. 
Wont upload. 

Any suggestions?

**Comment by Lorkris** [comment]
I used a ESP32-WROOM-32 and it works like a charme :)
Don't forget to put it in download mode!

It would be nice, if they could support ESP32-C6 Boards in the future ;)
